### ISSUE TITLE
Revenue per country data

### ISSUE THREAD

**Issue by Narnicwa** [forsbergplustwo/partner-metrics#102]
Hi,

I noticed that the "Revenue per country" pie chart data is a little bit off https://gyazo.com/78c3dd580a525409038ef3752422743d
It looks like it does not get data from Shopify.
Is it fixable or its just because of lack of data?

PS: I love Partner Metrics :)

---
I'm a human. Please be nice.

**Comment by forsbergplustwo** [comment]
Hey @Narnicwa , thanks for the message and glad you like the app 😊 Unfortunately it's due to the data, see: #7 for full details.
