### ISSUE TITLE
How to disable Cloudflare, AWS, mailer, for production?

### ISSUE THREAD

**Issue by jason-engage** [forsbergplustwo/partner-metrics#105]
I can get bin/dev to work fine, but when I switch to production, it always crashes asking for these additional logins. Any ways to run it bare bones on production?

**Comment by forsbergplustwo** [comment]
Unfortunately not really, they are needed for uploads of CSV file and login emails etc.

**Comment by jason-engage** [comment]
Ok, thanks for the reply

**Comment by jason-engage** [comment]
Ok, thanks for the reply
