### ISSUE TITLE
Shopify Partner API credentials are not accepted maybe due to the use of an older API version

### ISSUE THREAD

**Issue by tsirakis** [forsbergplustwo/partner-metrics#109]
We had the same issue with some internal tools getting this 404 error the last 3 days and was because we were using the API 2023-07 and not the 2024-07.

---
I'm a human. Please be nice.

**Comment by forsbergplustwo** [comment]
Thanks for the heads up @tsirakis , that looks to have been the issue 🎉 App is backfilling payments now so you should see up to date metrics shortly.
