### ISSUE TITLE
Importing a Payout is returning a 403

### ISSUE THREAD

**Issue by afunnydev** [forsbergplustwo/partner-metrics#75]
Thanks a lot for the platform. I've been looking for a tool like this since quite some time.

I am trying to import my payouts data inside the platform. Everytime I do it, looks like the page is breaking and I can see the errors in the Console/Network tabs. Here's what the platform looks like after a broken import:

![CleanShot 2023-09-21 at 14 08 21](https://github.com/forsbergplustwo/partner-metrics/assets/18277370/6af3fe13-d92c-489e-885a-f91fbf8ac4c6)

## Steps to reproduce

1) In Shopify, click on Export CSV and export All Payouts
2) Upload the received CSV in https://www.partnermetrics.io/imports/new
3) See the broken pages and no new data.

I also tried to ZIP the CSV because the box was telling to use a ZIP. Thanks!

**Comment by forsbergplustwo** [comment]
Thanks for the heads up @afunnydev. Fixed the CORS setup on Cloudflare, working now 😊

**Comment by forsbergplustwo** [comment]
Still some issues with Cloudflare vs local files, hang tight

**Comment by forsbergplustwo** [comment]
All fixed now, and importing nicely 🎉

![CleanShot 2023-09-21 at 21 35 54](https://github.com/forsbergplustwo/partner-metrics/assets/1411883/fd59ce82-81f5-4eee-b935-956a7bf214d5)

**Comment by afunnydev** [comment]
Thanks @forsbergplustwo ! I confirmed it's working and importing perfectly. Thanks for the quickness, much appreciated!
