### ISSUE TITLE
A number of challenges

### ISSUE THREAD

**Issue by mqsley** [forsbergplustwo/partner-metrics#87]
- I added my partner API credentials, Is there a button I should push to sync?
- No where does it show which app I am looking at the numbers for
- How do I switch between partner apps in the dashboard

---
I'm a human. Please be nice.

**Comment by mqsley** [comment]
I also branched to see if I could add a monthly email that would just do top line app revenue every month - hitting some weird errors with your DB when trying to add an additional api key field to users

**Comment by forsbergplustwo** [comment]
- API sync happens daily using rake task
- Yes it does. At the top of every page once you have data
- What do you mean?
- Have you added the encryption keys? Sharing the error would be the first step

**Comment by mqsley** [comment]
Apologies - 1st OS project I've ever tried to contribute to.
Now that it has pulled data I see I was wrong on 2 & 3. Although it only sees 2 of my apps, there are 4 (3 have charges)

I have not added encryption keys...

**Comment by forsbergplustwo** [comment]
Thanks for the follow up 👍 

The app will only show data related to apps that have payed out money to you in the period imported. The app works using the Payout data from Shopify, so it won't show anything for free apps, or apps that have no payed out charges.

Strange on the DB issue. Have you run the commands as shown on the "First time setup" section of the README: https://github.com/forsbergplustwo/partner-metrics#first-time-setup

If you have, and you are still seeing errors, please provide the log output showing the error here so I can take a look 😊
