### ISSUE TITLE
Connection problem of Sideqik with Redis

### ISSUE THREAD

**Issue by ankushkatiyar** [forsbergplustwo/partner-metrics#88]
Hello Team, 

I'm trying to set up this app on a linux machine.

**Server details:**

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy 

Problem statement: 

When I execute the bin/dev command as mentioned in the readme.md file, then I can see this error

<img width="1376" alt="Screenshot 2023-11-21 at 7 41 29 PM" src="https://github.com/forsbergplustwo/partner-metrics/assets/25097302/27b0d102-2961-40d5-9a02-5588547c922f">

Sideqik is trying to connect with Redis but it's not connected successfully.

**Comment by forsbergplustwo** [comment]
localhost:4000

or

https://0.0.0.0:4000/

**Comment by ankushkatiyar** [comment]
Hi @forsbergplustwo 

As you can see in the dev environment app is listening on http://0.0.0.0:4000, but it's local for that server only.
When I want to access it globally via browser how it will be accessible? Do I need to expose port 4000 that running on the server or i need to create a tunnel for this?

When I'm to access that port with sever ip than still it's not working

**Comment by ankushkatiyar** [comment]
Thanks, @forsbergplustwo I just checked, and due to a networking issue I'm not able to access it.

**Comment by forsbergplustwo** [comment]
Glad you got it worked out 😊

**Comment by ankushkatiyar** [comment]
I can see this error as well 
<img width="1407" alt="Screenshot 2023-11-22 at 1 26 00 PM" src="https://github.com/forsbergplustwo/partner-metrics/assets/25097302/e3df3573-4666-41f7-8d1a-30b2be0b8e19">

**Comment by forsbergplustwo** [comment]
Hey @ankushkatiyar, "Broken pipe" error is unrelated to the app code, or the action you are taking in the app. Most likely related to your linux setup and it unable to make the correct connections to db etc. Unfortunately it's not possible for me to troubleshoot your local setup, so no idea why it's throwing these errors.

**Comment by ankushkatiyar** [comment]
Thanks @forsbergplustwo for the update. It looks like a database connection issue. I just restarted db connection and it's working fine now.

**Comment by ankushkatiyar** [comment]
Hi @forsbergplustwo 
When i start the app in linux environment using command "/bin/dev" then app will execute in foreground and when i convert this foreground progress to background then application is working in browser but database connection lost.

<img width="1212" alt="Screenshot 2023-11-22 at 5 23 37 PM" src="https://github.com/forsbergplustwo/partner-metrics/assets/25097302/86f73bc1-c13f-4073-9c4b-2b783b1ae53e">

As you can see in my attached image, process is working in foreground and app working normally with database connection
When i covert this process in background and close terminal then application working in browser, but database conenction lost

Any idea how to solve this problem? Or i need to change something in app ?

**Comment by ankushkatiyar** [comment]
Hi @forsbergplustwo 
Application setup has been done in the linux machine. I also saved Shopify Partner API credentials in application but i don't see any imported data in APP. I need to do something else for importing or data will import automatically?

**Comment by ankushkatiyar** [comment]
Hi @forsbergplustwo 
It's almost more than 18hours after save Shopify partner credentials. But still i don't see any imported data in APP. 
Can you let me know how much time it will take to import data and how data will import in APP, it's via cron jobs or something else?

**Comment by forsbergplustwo** [comment]
See: https://github.com/forsbergplustwo/partner-metrics/blob/main/lib/tasks/import_all_from_partner_api.rake

Run it daily.

**Comment by ankushkatiyar** [comment]
Hi @forsbergplustwo Thanks for the update. I checked your note, i'll take care of it.
After execution of import_all_from_partner_api , i can see import status is set as scheduled in APP

<img width="1025" alt="Screenshot 2023-11-24 at 1 36 11 PM" src="https://github.com/forsbergplustwo/partner-metrics/assets/25097302/7ce4d84d-4bb7-45bf-a242-4c6fa15a1ad9">

can you please let me know badge status will set completed automatically and data will import in APP or i need to execute other command?
