### ISSUE TITLE
Import status modification

### ISSUE THREAD

**Issue by ankushkatiyar** [forsbergplustwo/partner-metrics#90]
Hi @forsbergplustwo 
After execution of import_all_from_partner_api , i can see import status is set as scheduled in APP

<img width="1423" alt="Screenshot 2023-11-24 at 1 44 45 PM" src="https://github.com/forsbergplustwo/partner-metrics/assets/25097302/09b4865f-0534-4ca0-b674-c5a2a452c2cb">

Can you please let me know badge status will set completed automatically and data will import in APP or i need to execute other command?

**Comment by ankushkatiyar** [comment]
Hi @forsbergplustwo yes, `bin/dev` is already working in linux machine

<img width="1330" alt="Screenshot 2023-11-24 at 5 04 42 PM" src="https://github.com/forsbergplustwo/partner-metrics/assets/25097302/d4a26a7c-0f82-4d74-8748-6a52b0f8ae6c">

**Comment by ankushkatiyar** [comment]
Is it related to SSL or something else? 
I'm accessing application in the linux machine with ip

**Comment by ankushkatiyar** [comment]
Hi @forsbergplustwo 
I created some logs of worker, i'll share it with you. So you can analyse it in better way.

**Comment by ankushkatiyar** [comment]
Hi @forsbergplustwo 
FYI, when i execute import command `bin/rails import_all_from_partner_api`, i can see task added in scheduled status
You can access import log in this file https://ankush-metrics.s3.ap-south-1.amazonaws.com/import.txt and worker log in https://ankush-metrics.s3.ap-south-1.amazonaws.com/worker_error.txt

you can check in worker log, after execution of Shopify API then status changed scheduled to failed

<img width="1440" alt="Screenshot 2023-11-25 at 11 55 44 AM" src="https://github.com/forsbergplustwo/partner-metrics/assets/25097302/628fc5e6-e596-459e-b093-01f747568751">

I hope this log debug problem easily

**Comment by forsbergplustwo** [comment]
Hi @ankushkatiyar , I’m sorry but I cannot debug your Linux setup or go through your logs for you. I’m happy to take a look at any actual bugs you are able to clearly point out with stack traces etc.

Please use the hosted version of the app available at https://partnermetrics.io
